name: ZAP SCAN - DAST
on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'


      - name: Create sarif file from zaproxy results         
        uses: SvanBoxel/zaproxy-to-ghas@main       
      - name: Upload SARIF file         
        uses: github/codeql-action/upload-sarif@v1         
        with:           
          sarif_file: results.sarif


